version: "3.4"

services:
  unopsbackend:
    image: unopsbackend
    volumes:
      - ./:/app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=unops
    depends_on:
      - unopsbackend
